// <auto-generated />
namespace AccessoADatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _4Migracion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4Migracion));
        
        string IMigrationMetadata.Id
        {
            get { return "202006091304251_4Migracion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
