// <auto-generated />
namespace AccessoADatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class rel_contrato_entrada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rel_contrato_entrada));
        
        string IMigrationMetadata.Id
        {
            get { return "202105131937481_rel_contrato_entrada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
